config/routes.rb
Rails.application.routes.draw do
  root "bands#index"

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :integer          not null, primary key
#  title          :string           not null
#  band_id        :integer          not null
#  recording_type :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Album < ActiveRecord::Base
  RECORDING_TYPES = %w(live studio)

  validates :title, :recording_type, presence: true
  validates :recording_type, inclusion: RECORDING_TYPES
  validates :band, presence: true

  belongs_to(
    :band,
    class_name: :Band,
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    class_name: :Track,
    foreign_key: :album_id,
    primary_key: :id,
    dependent: :destroy
  )
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many(
    :albums,
    class_name: :Album,
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many :tracks, through: :albums, source: :tracks

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  title      :string           not null
#  status     :string           not null
#  lyrics     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base
  STATUS = %w(bonus regular)

  validates :album, presence: true
  validates :title, :status, presence: true
  validates :status, inclusion: STATUS

  belongs_to(
    :album,
    class_name: :Album,
    foreign_key: :album_id,
    primary_key: :id
  )

  has_one :band, through: :album, source: :band
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username,
            :email,
            :password_digest,
            :session_token,
            presence: true

  validates :username, :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, length: { minimum: 10 }
  after_initialize  :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return user if user && user.valid_password?(password)
    return nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_signed_in!

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @album = Album.new
    @band = @album.band
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    bandid = @album.band_id
    @album.destroy
    redirect_to band_url(bandid)
  end

  def album_params
    params.require(:album).permit(:band_id, :title, :recording_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def log_in!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def log_out!
    current_user.try(:reset_session_token)
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_signed_in!

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.save
      log_in!(user)
      redirect_to bands_url
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input type=\"hidden\"
           name=\"authenticity_token\"
           value=\"#{form_authenticity_token}\">".html_safe
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) : albums_url %>
<% http_method = album.persisted? ? "patch" : "post" %>
<% submit_text = album.persisted? ? "Edit Album" : "Add Album" %>

<form action="<%= action_url %>" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="_method" value="<%= http_method %>">
  <label for="album_title">Title</album>
  <input type="text" name="album[title]" id="album_title" value="<%= @album.title %>">
  <br>
  <label for="album_band_id">Band</label>
  <select name="album[band_id]" id="album_band_id">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>"
              <%= "selected" if @album.band_id == band.id %>>
        <%= band.name %>
      </option>
    <% end %>
  </select>
  <br>
  <% Album::RECORDING_TYPES.each do |type| %>
    <label>
    <input type="radio"
           name="album[recording_type]"
           value="<%= type %>"
           <%= "checked" if @album.recording_type == type %>>
    <%= type %>
    </label>
  <% end %>
  <br>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/albums/edit.html.erb
<h1>Edit album</h1>

<%= render "form",  album: @album %>

app/views/albums/new.html.erb
<h1>Add New Album</h1>

<%= render "form", album: @album %>

app/views/albums/show.html.erb
<h1>Special Page for <%= @album.title %></h1>

<p>All the tracks will go here + there will be a link to all the tracks.</p>
<br>

<%= link_to "Edit Album", edit_album_url(@album) %>
<%= button_to "Delete Album", album_url(@album), method: :delete %>
<%= link_to "Add New Album", new_band_album_url(@album.band) %>
<%= link_to "Band", band_url(@album.band_id) %>

app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% action_method = band.persisted? ? "patch" : "post" %>
<% submit_text = band.persisted? ? "Edit Band" : "Add Band" %>

<form action="<%= action_url %>" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="_method" value="<%= action_method %>">
  <label for="band_name">Name</label>
  <input type="text" name="band[name]" id="band_name" value="<%= @band.name %>">
  <br>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<%= render "form", band: @band %>

app/views/bands/index.html.erb
<h1>Bands</h1>

<ul>
  <% @bands.each do |band| %>
    <li><%= link_to band.name, band_url(band) %></li>
  <% end %>
</ul>

<%= link_to "Add New Band", new_band_url %>

app/views/bands/new.html.erb
<h1>Add New Band</h1>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1>Special Page for <%= @band.name %></h1>

<ul>
<% @band.albums.each do |album| %>
  <li><%= link_to album.title, album_url(album) %></li>
<% end %>
</ul>

<%= link_to "Edit Band", edit_band_url(@band) %>
<%= button_to "Delete Band", band_url(@band), method: :delete %>
<%= link_to "Bands Index", bands_url %>
<%= link_to "Create Album", new_band_album_url(@band) %>

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |msg| %>
    <li><%= msg %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <ul class="nav nav-pills">
        <% if signed_in? %>
          <li>Welcome, <%= @current_user.username %></li>
          <li><%= button_to "Sign Out", session_url, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_url %></li>
          <li><%= link_to "Sign In", new_session_url %></li>
        <% end %>
      <ul>
    </div>
  </div>
</nav>

<%= render "layouts/errors" %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up Now</h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token_input %>
  <label for ="user_username">Username</label>
  <input type="text" name="user[username]" id="user_username">
  <br>
  <label for="user_email">Email</label>
  <input type="text" name="user[email]" id="user_email">
  <br>
  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>
  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1>Profile page for <%= @user.name %></h1>

Your email: <%= @user.email %>